apiVersion: v1
kind: Pod
metadata:
  name: kuma-entry
spec:
  containers:
    - name: test-container
      image: python:3.8-slim
      command: ["/bin/bash"]
      args:
        - -c
        - |
          export KUMA_USER=
          export KUMA_PASSWD=
          pip install uptime-kuma-api==0.9.0
          echo "import os" |tee -a entry.py
          echo "from uptime_kuma_api import UptimeKumaApi, MonitorType" |tee -a entry.py
          echo "api = UptimeKumaApi('http://uptime-kuma-service.kuma:3001')" |tee -a entry.py
          echo "api.login(os.environ['KUMA_USER'], os.environ['KUMA_PASSWD'])" |tee -a entry.py
          echo "result = api.add_monitor(type=MonitorType.HTTP, name='sofe-httpd', url='https://httpd.joshlab.home')" |tee -a entry.py
          echo "print(result)" |tee -a entry.py
          echo "api.disconnect()" |tee -a entry.py
          python entry.py
      # envFrom:
      # - configMapRef:
      #    name: flask
  restartPolicy: Never