apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox
      command: [ "/bin/echo", "$(DB_HOST) $(DBNAME) $(DBUSER)" ]
      env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: flask-postgres
              key: DB_HOST
        - name: DBNAME
          valueFrom:
            configMapKeyRef:
              name: flask-postgres
              key: DBNAME
        - name: DBUSER
          valueFrom:
            configMapKeyRef:
              name: flask-postgres
              key: DBUSER
  restartPolicy: Never