---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxfssl
  name: nginxfssl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxfssl
  template:
    metadata:
      labels:
        app: nginxfssl
    spec:
      containers:
      - image: nginxdemos/hello
        name: nginxfssl
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: nginxfssl
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxfssl
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginxfssl
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nginx.joshlab.home`)
      kind: Rule
      services:
        - name: nginxfssl
          port: 80
  tls:
    certResolver: letsencrypt