apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.11.5
    chart: promtail
    helm:
      parameters:
        - name: config.clients[0].url
          value: http://loki-loki-distributed-gateway.monitoring.svc.cluster.local/loki/api/v1/push
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true  
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).